package-name: TSR.ObjectUVs
visual-name: TSR ObjectUVs
destination-folder: Assets/VRLabs/Toony Standard Rebuild Modules/TSR Object Space UVs
extra-generated-meta:
  - path: Assets/VRLabs
    guid: 652a1ba5b00554143bc9a76307dbc4e8
  - path: Assets/VRLabs/Toony Standard Rebuild Modules
    guid: d3d02b5b274410849ba3e6c360e2f005
  - path: Assets/VRLabs/Toony Standard Rebuild Modules/TSR Object Space UVs
    guid: 90cb63d4947391e4f8d54ba099921250